baseURL = "https://vtsugi1.github.io/site-clinica-hugo/"
languageCode = "pt-BR"
title = "Clínica de Psicologia"
theme = "PaperMod"

[params]
  author = "Clínica de Psicologia [Nome]"
  description = "Site institucional da Clínica de Psicologia [Nome]."
  # Configurações do tema PaperMod
  defaultTheme = "light"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  
  [params.homeInfoParams]
    Title = "Clínica de Psicologia"
    Content = """
    Bem-vindo à nossa clínica de psicologia. Oferecemos diversos serviços para promover saúde mental e bem-estar.

    - Atendimento psicológico para diferentes públicos
    - Supervisão clínica para profissionais
    - Atividades em grupo e terapêuticas
    """

[menu]
  [[menu.main]]
    identifier = "quem-somos"
    name = "Quem Somos"
    url = "/quem-somos/"
    weight = 1

  [[menu.main]]
    identifier = "atendimento"
    name = "Atendimento Psicológico"
    url = "/atendimento/"
    weight = 2

  [[menu.main]]
    identifier = "supervisao"
    name = "Supervisão Clínica"
    url = "/supervisao/"
    weight = 3

  [[menu.main]]
    identifier = "contato"
    name = "Contato"
    url = "/contato/"
    weight = 6